#!/usr/bin/env php
<?php
// application.php

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        define('ALAUDA_COMPOSER_INSTALL', $file);
        break;
    }
}
require ALAUDA_COMPOSER_INSTALL;

use Symfony\Component\Console\Application;
use Xjchen\Alauda\Command\AuthProfileCommand;
use Xjchen\Alauda\Command\TokenClearCommand;
use Xjchen\Alauda\Command\ServiceListCommand;
use Xjchen\Alauda\Command\ServiceDescribeCommand;
use Xjchen\Alauda\Command\ServiceDestroyCommand;
use Xjchen\Alauda\Command\ServiceLogCommand;
use Xjchen\Alauda\Command\InstanceListCommand;
use Xjchen\Alauda\Command\InstanceDescribeCommand;
use Xjchen\Alauda\Command\UpReverseProxyCommand;
use Xjchen\Alauda\Command\DatabaseCreateCommand;
use Xjchen\Alauda\Command\UpCommand;

$application = new Application();
$application->add(new AuthProfileCommand());
$application->add(new TokenClearCommand());
$application->add(new ServiceListCommand());
$application->add(new ServiceDescribeCommand());
$application->add(new ServiceDestroyCommand());
$application->add(new ServiceLogCommand());
$application->add(new InstanceListCommand());
$application->add(new InstanceDescribeCommand());
$application->add(new UpReverseProxyCommand());
$application->add(new DatabaseCreateCommand());
$application->add(new UpCommand());
$application->run();
